### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#10]
Server crash 
https://gist.github.com/bigenergy/24831302999d5f4f3f83c18dd13de6e3

**Comment by bigenergy** [comment]
first I built the very constructions of thaumatoriums without activating them with salis mundus
And first I put collectors on them and threw the craft of alumentum there
![image](https://user-images.githubusercontent.com/17977139/95609794-fbf55280-0a67-11eb-9fe7-46cd400ca8f9.png)

And after activating and connecting the collectors to the system, a series of server crashes began
![image](https://user-images.githubusercontent.com/17977139/95609819-06afe780-0a68-11eb-9725-516bf9232801.png)

Crash in single player mode too
https://gist.github.com/bigenergy/a847bc5b07d8b0c5330e541858c5a1f8

**Comment by tth05** [comment]
1. Did you have any GUIs open during the crash or before the crash?
2. Are just using refined and thaumcraft on a new world? 
3. Do you consistently get this crash or did it just happen randomly?

I'm unable to re-produce this, although I'm unsure if I understood your reproduction steps correctly. I just have a crafter with a recipe connected to a thaumatorium.

**Comment by tth05** [comment]
I've added a fix in dd352fa031527c9533dd1dd38e7c6ac1c76c7985 that should prevent the crash, but I'm still uncertain how it even ever happenend.

**Comment by bigenergy** [comment]
@tth05 pls push release

**Comment by tth05** [comment]
Done
