### ISSUE TITLE
I forgot a line in the 1.12 version of the grid performance improvements

### ISSUE THREAD

**Issue by ScoreUnder** [tth05/morerefinedstorage#11]
I should have added `this.gui.updateScrollbar();` at the end of `postChange` to ensure that crafting recipes (etc) can't scroll off the bottom while new unique items are coming into the system. I have only confirmed that this is a problem in RS on 1.16, but I suspect it is be the same in 1.12. Of course changing the contents of the search box will refresh the scroll bar anyway, so I suspect anyone searching for a crafting recipe will never notice this.

**Comment by tth05** [comment]
Thanks a lot coming here and telling me this!
Fixed in 828050799e0a5042f724648be8f27d7a0aaed055

**Comment by bigenergy** [comment]
Nice work!
@tth05 pls push release)

**Comment by tth05** [comment]
It's already in the new one :)

**Comment by bigenergy** [comment]
oh, thx
