### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#12]
#### Issue description:
server crash in start 

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage: 2.1.7

Does this issue occur on a server? yes

https://pastebin.com/9hmaPBKJ

**Comment by bigenergy** [comment]
morerefinedstorage-2.1.6 does not crash

**Comment by tth05** [comment]
Weird that I didn't get this during my testing. I'll just the revert the change that seems to break it.

**Comment by tth05** [comment]
70ab474fa330236e3393f9ab5f82810eeb13f777

**Comment by bigenergy** [comment]
@tth05 pls push release, since the latest version doesn't work

**Comment by tth05** [comment]
@bigenergy done, I was just waiting for your PR
