### ISSUE TITLE
Performance v 2.2.2

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#16]
#### Issue description:
https://spark.lucko.me/#exNtnGPNkN

![image](https://user-images.githubusercontent.com/17977139/99829220-0f1e3680-2b6d-11eb-9ab4-0577477fe536.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest 
- Refined Storage: 2.2.2

Does this issue occur on a server? [yes/no] yes

**Comment by tth05** [comment]
Do you have a spark with 2.2.1? This by itself doesn't say much

**Comment by bigenergy** [comment]
> Do you have a spark with 2.2.1?

maybe this https://spark.lucko.me/#56ACPHcDZW

**Comment by tth05** [comment]
Closing this for now, because there's nothing of significance in both sparks
