### ISSUE TITLE
StorageTech server crash

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#18]
take a custom disk (storage tech) from JEI and crash server
https://pastebin.com/1eWNYbKx

**Comment by bigenergy** [comment]
https://github.com/JavaPowerFR/StorageTech/blob/1.12/java/javapower/storagetech/item/ItemDiskCustom.java#L76

**Comment by tth05** [comment]
I'm not supporting those api calls anymore. You can edit the bytecode and remove that call if you want.

**Comment by bigenergy** [comment]
I made fork - https://github.com/bigenergy/StorageTech-MoreRefinedStorage
