### ISSUE TITLE
Refined Storage API for OpenComputers not working

### ISSUE THREAD

**Issue by Pelotrio** [tth05/morerefinedstorage#2]
#### Issue description:

Can not access the fields of an Itemstack in oc. 

#### What happens:
After retrieving the items of the system you are unable to access any information of them because everything returns null.

#### Steps to reproduce:
1. Make an opencomputers setup
2. Get the items of the refined storage system
3. Try to access the fields of an itemstack (name, label, etc)

#### Version (make sure you are on the latest version before reporting):

- Minecraft:   1.12
- Forge:
- Refined Storage: latest

#### Does this issue occur on a server? [yes/no]
yes

**Comment by tth05** [comment]
Fixed in ac1a8d4
