### ISSUE TITLE
Crashing when using Refined Avaritia extreme pattern in crafter.

### ISSUE THREAD

**Issue by lokep001** [tth05/morerefinedstorage#20]
#### Issue description:
Crashes when using extreme patterns
#### What happens:
I used Refined Avaritia to make a crafting pattern for crystaltine. Made the pattern and then put into crafter (above automation interface) and then server crashes.
#### What you expected to happen:
It wouldn't crash
#### Steps to reproduce:
1. Make extreme pattern
2. Put in crafter
3. Kaboom
...

#### Version (make sure you are on the latest version before reporting):
- Refined Avaritia: 2.6
- Minecraft: 1.12.2
- Forge: 2847
- Refined Storage: 2.2.6

Does this issue occur on a server? [yes/no]
Don't know
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://pastebin.com/YHiwpZnK

**Comment by tth05** [comment]
Hey, sadly because of time constraints I stopped working on providing compatibility with old mods. The code base for this RS version has changed in a some parts which does lead to issues like this.
This mod was initially made for private use, but I thought I could make it public if people want to use it.

**Comment by lokep001** [comment]
Oh right, that's fine. Best of luck to you!

**Comment by Pelotrio** [comment]
Maybe in the future

**Comment by lokep001** [comment]
> Maybe in the future

well that would be great because then i could play exisiting expert packs on 1.12.2 with the new RS :D

**Comment by lokep001** [comment]
Just tried RS large patterns and it also crashes with the same error and same way.

Edit: should’ve put crash log in https://pastebin.com/7APHNWF0

**Comment by tth05** [comment]
I'll look at it tomorrow, maybe it's an easy fix

**Comment by lokep001** [comment]
Thanks! RSLargePatterns is probably the better mod to look at as refined avaritia has been discontinued.

**Comment by tth05** [comment]
Fixed in 9a2f2e4b85e35c67265bf526d69067573a6e5b96
New release soon

**Comment by lokep001** [comment]
thank you so much :D this works with RSlargepatterns too? if so that would be great because that supports processing patterns too. but even if not so thank you so much for your work :D

**Comment by tth05** [comment]
> thank you so much :D this works with RSlargepatterns too? if so that would be great because that supports processing patterns too. but even if not so thank you so much for your work :D

I haven't tested it, but both mods work in a similar way so it could work.

**Comment by tth05** [comment]
Release is out.

**Comment by lokep001** [comment]
> > thank you so much :D this works with RSlargepatterns too? if so that would be great because that supports processing patterns too. but even if not so thank you so much for your work :D
> 
> I haven't tested it, but both mods work in a similar way so it could work.

yeah just tested it, works perfectly! Thanks :D
