### ISSUE TITLE
Incompatibility with More Refined Storage (not this mod)

### ISSUE THREAD

**Issue by xemnes** [tth05/morerefinedstorage#22]
#### Issue description:
More Refined Storage which adds large disk drives is incompatible with this fork.

#### What happens:
game crashes when trying to use a disk from the More Refined Storage mod (not this mod) simply holding a disk from the addon caused the crash.
https://www.curseforge.com/minecraft/mc-mods/more-refined-storage

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2 
- Forge: 2847
- Refined Storage: 2.2.7

Does this issue occur on a server? [yes/no]
yes

#### If a (crash)log is relevant for this issue, link it here:
https://paste.mod.gg/guyedapofi.mccrash

**Comment by embeddedt** [comment]
Heads up: https://github.com/tth05/morerefinedstorage/issues/20#issuecomment-782185354

One thing I am unsure of is why a 64 million item storage disk is necessary when mods like Storage Drawers and QuantumStorage exist. :confused:

**Comment by xemnes** [comment]
oh thats a pitty, i could attempt to do it myself then, though i guess i need to know what exactly changed to know how to fix it. guess loading up an ide will probably give me some info.

as for the big sotrage disk, the options there if i decide to use it, i do like the convenience of just chucking stuff in a massive storage box not having to worry about sorting.

**Comment by embeddedt** [comment]
If it's any help, the crash appears to be caused by a reference to the RS 1.6 migration helpers, which have been removed from this fork. I tried to find a GitHub repository for the mod so I could point you to where they were being used, but I couldn't find the repository.

**Comment by xemnes** [comment]
the repo for the addon? yeah sadly it doesnt seem to be open source. i have asked the dev if i could have the source, waiting for a response.

**Comment by JayJay1989** [comment]
Its indeed closed source. Just dm me on discord, we can figure something out

**Comment by tth05** [comment]
I guess I can add the class back with an empty implementation, this is pretty annoying :/

**Comment by Pelotrio** [comment]
Pretty ironic that morerefindstorage is not compatible with More Refined Storage

**Comment by tth05** [comment]
:D

**Comment by JayJay1989** [comment]
> Pretty ironic that morerefindstorage is not compatible with More Refined Storage

Not quite, `morerefinedstorage` is a lot older than this mod and will probably break compatibility to the original and this forked version

**Comment by Pelotrio** [comment]
This fork removed some unnecessary stuff that older mods still depend on. What I sad was just a joke regarding the name nothing else. @JayJay1989

**Comment by JayJay1989** [comment]
This can be closed https://www.curseforge.com/minecraft/mc-mods/more-refined-storage/files/3232011

**Comment by tth05** [comment]
Nice!
