### ISSUE TITLE
Change shiftclick behavior in crafting grid

### ISSUE THREAD

**Issue by hjae78** [tth05/morerefinedstorage#25]
#### Steps to reproduce:
1. Have a recipe for any item.
2. Have one or more of said item.
3. Go into crafting grid, press shift and see said item disappear.

**Comment by tth05** [comment]
I'm not quite sure if I understand you correctly. Do you have a video example?

If you want to craft an item you have to use Ctrl+Shift+Click

**Comment by hjae78** [comment]
Item in system:
![image](https://user-images.githubusercontent.com/54247183/118368989-f71af300-b5a2-11eb-8fc9-54d124dad1ed.png)
Pressing shift:
![image](https://user-images.githubusercontent.com/54247183/118369017-1285fe00-b5a3-11eb-85a2-57c9bc6dee76.png)
Item out of system: 
![image](https://user-images.githubusercontent.com/54247183/118369426-98a24480-b5a3-11eb-854d-87c5f8c4086b.png)
Item out of system pressing shift: 
![image](https://user-images.githubusercontent.com/54247183/118369434-a35cd980-b5a3-11eb-8feb-aa144a2f4474.png)

**Comment by tth05** [comment]
That's looks extremely weird. Pressing shift is not supposed to show only craftable items. It's only meant to prevent sorting

**Comment by tth05** [comment]
- Is the item completely gone afterwards? Or does it come back if you re-open the grid or search something else?
- What is your storage setup like? External storages, drives, etc.
- Do all items instantly vanish when you press shift or is there a delay?

**Comment by hjae78** [comment]
The item does not disappear, releasing shift brings it back.

Everything in drives, very very few items in drawers and chests (only large passive amounts, nothing you see I'm screenshots)

Sometime there's a delay, i think the items disappearing only happen when my mouse is over one of the "item cells" in the grid. If the mouse is outside the grid window it doesn't happen

**Comment by tth05** [comment]
Could you remove every single external storage and tell me if it still happens?

**Comment by hjae78** [comment]
When I remove all external storage (and the majority of my network) it behaves as I would expect. I simply broke the cable going from my controller to my machines. On the network was only controller, non-processing crafters and disk storage.

**Comment by tth05** [comment]
I did some changes to only prevent a single stack from being sorted when holding shift on it. Previously the whole grid prevented sorting which caused all items to just vanish when the storage cache invalidates (probably because of the external storages).

This should fix all items vanishing.
