### ISSUE TITLE
Wrong coun items

### ISSUE THREAD

**Issue by ferreiraalex** [tth05/morerefinedstorage#28]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge:  2855 latest
- Refined Storage: lates your version

Does this issue occur on a server? [no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
https://i.imgur.com/uFq4OHM.png
https://i.imgur.com/BONITHw.png

**Comment by tth05** [comment]
Fixed in 8033327a456ec2f4d5becb00048427f15ddee709, although what YABBA does is just really dum.
