### ISSUE TITLE
cant use only template form

### ISSUE THREAD

**Issue by ferreiraalex** [tth05/morerefinedstorage#29]
why if i choose only template form in terminal and prees to create anything its not show in this menu? in original its work good

**Comment by tth05** [comment]
What? Can you provide screenshots?

**Comment by ferreiraalex** [comment]
YE! can you wait one hour i need to start oroginal rs and yor version

**Comment by ferreiraalex** [comment]
its original RS 
refinedstorage-1.6.16
https://imgur.com/a/ShsL1yA
and its
morerefinedstorage-2.2.10
https://imgur.com/a/3NnHhZa
if i have crafted items not show in list

**Comment by tth05** [comment]
Do you mean that in the "Only craftables" mode it doesn't show the items that you already have of that item? If so, that is intended behavior.
![image](https://user-images.githubusercontent.com/36999320/127522872-0ff24089-57c1-4b43-9aeb-e25dd8803b54.png)
![image](https://user-images.githubusercontent.com/36999320/127522906-15e5e58b-712a-410a-854e-9e97e7496604.png)

**Comment by ferreiraalex** [comment]
oh ye, but i think its not comfortable, but if you think another no problem
