### ISSUE TITLE
Buckets deleted if autocrafting with them

### ISSUE THREAD

**Issue by csuarezmtz** [tth05/morerefinedstorage#36]
#### Steps to reproduce:
1. Autocraft 4x sawdust (Thermal) + 1 water filled bucket = 6 paper
2. Count the number of buckets crafted (plus iron usage)
3. Validate if buckets remain in the system after crafting is done
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.2.2
- Refined Storage: 1.9.15

Does this issue occur on a server? [yes/no] no

#### If a (crash)log is relevant for this issue, link it here:
No crash

**Comment by embeddedt** [comment]
I think you opened this on the wrong repository. This is an unofficial fork
for 1.12, not the 1.16 version.

**Comment by tth05** [comment]
The official repository can be found here: https://github.com/refinedmods/refinedstorage
