### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#4]
#### Issue description:
Server crashes when switching pulverizer (from Thermal Expansion) mode connected to refined storage
#### What happens:
crash server
#### Steps to reproduce:
Connect the pulverizer to the refined storage, change the input ports and get a crash

![image](https://user-images.githubusercontent.com/17977139/91766543-64d4e980-ebe3-11ea-9ac0-810145e9a5c9.png)
![image](https://user-images.githubusercontent.com/17977139/91766986-1bd16500-ebe4-11ea-8ced-be53bf185744.png)
![image](https://user-images.githubusercontent.com/17977139/91766992-1f64ec00-ebe4-11ea-80a0-899e621ab6bb.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest
- Refined Storage: 2.1.1

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/bs9g2qyH

**Comment by tth05** [comment]
I'll fix it today.

Thanks for reporting bugs, I didn't know anyone even uses this.

**Comment by tth05** [comment]
fixed in 25e35d7b8f7285a9b41e2aa8df666448aca6f162
