### ISSUE TITLE
RebornStorage(fork v3.3.5.2) does not support the latest version of moremorerefinedstorage

### ISSUE THREAD

**Issue by 200542053** [tth05/morerefinedstorage#40]
#### Issue description:
RebornStorage (fork v3.3.5.2) does not support the latest version of moremorerefinedstorage anymore
#### What happens:
cannot use the new disks from RebornStorage
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- Refined Storage:v3.3.5.2

Does this issue occur on a server? [yes]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Pelotrio** [comment]
What exactly does it mean that you can't use the disk from the RebornStorage fork? Does your game crash, can't you insert the disk or what is the problem?

**Comment by 200542053** [comment]
Sorry to interrupt, I solved the problem, it was one of the players on my server who couldn't import items into disks.
