### ISSUE TITLE
Item Extraction 

### ISSUE THREAD

**Issue by CrossVas** [tth05/morerefinedstorage#42]
Hey, found your fork and it's really nice to see new features from 1.12+ version here as well as some improvements. I have one question though. Is it possible to change single item extraction button from middle click to SHIFT/CTRL + R-Click for instance (like AE2 does it)? Because to be honest having it on middle click isn't that convenient and easy to use.

**Comment by tth05** [comment]
Seems like a bit excessive of a keybind to me. Not sure if I'd be a fan it. I can also recommend scrolling `Shift + Scroll Whell` to extract items. I basically never use middle click because of this.

**Comment by CrossVas** [comment]
Uuuuh, my bad. I've tried the wrong scrolling direction. Thank you very much. Issue closed.
