### ISSUE TITLE
Request: make creative wireless upgrade work across dimensions

### ISSUE THREAD

**Issue by freopt** [tth05/morerefinedstorage#47]
title

**Comment by tth05** [comment]
We believe this change diverges to much from the original refined storage version. For the same reason we never changed the speed of any upgrades or similar.

**Comment by embeddedt** [comment]
@freopt You can use my fork of [RSInfiniteWireless](https://github.com/embeddedt/RSInfiniteWireless/releases/tag/v1.2.0) instead. If you place one in each dimension, I think you will get a similar effect.

**Comment by tth05** [comment]
You can also make the creative range upgrade craftable 👍
