### ISSUE TITLE
Thaumic Grid incompatible

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#5]
#### Issue description:
Thaumic Grid incompatible
#### What happens:
Crash
#### Steps to reproduce:
1. Install RS (morerefinedstorage)
2. Install Thaumic Grid (https://www.curseforge.com/minecraft/mc-mods/thaumic-grid)
3. Install Thaumcraft 6.1
4. Start client or server and get crash https://pastebin.com/6nVNMuj1

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest
- Refined Storage: latest

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://pastebin.com/6nVNMuj1

**Comment by tth05** [comment]
That's what I get for trying to organize stuff into more packages I guess...

**Comment by tth05** [comment]
d6485fa46072db507c05d690173c0f30416c09ed

**Comment by tth05** [comment]
fixed in d6485fa

**Comment by bigenergy** [comment]
@tth05 pls push new release

**Comment by tth05** [comment]
Sorry, forgot about this

**Comment by bigenergy** [comment]
@tth05 not fixed https://pastebin.com/MEFm7BPL

**Comment by tth05** [comment]
Yeah I was expecting that it's not just one class

**Comment by tth05** [comment]
I've decided that I have to revert way too much to make this compatible again, so I will leave this unsupported for now. I might be able to make a custom version of ThaumicGrid within the next week that is compatible with this.

**Comment by tth05** [comment]
See #6

**Comment by bigenergy** [comment]
@tth05 This addon has only one block, I think it is easier for you to implement it in your mod.

In general, I would like to see "Thaumic Storage".. something like an addon with support for taumcraft (analog Thaumic Energistics). 
At one time the author of the original refined storage abandoned such ideas

**Comment by bigenergy** [comment]
You could also upload your mod on the curseforge under the guise of a modified and improved refined storage
i think your mod will be popular

**Comment by tth05** [comment]
Implementing it directly might actually be a good idea! If you have any suggestions for it then please put them in the new issue.
Also I'm still unsure if I want to put it on Curseforge. I'll keep it here for now
