### ISSUE TITLE
Support for Refined Storage: Requestify

### ISSUE THREAD

**Issue by aking4125** [tth05/morerefinedstorage#58]
Hello,

Using this fork of RS causes the game to crash upon load with [Refined Storage: Requestify](https://legacy.curseforge.com/minecraft/mc-mods/rs-requestify/files/2696433)

https://github.com/Buuz135/RS-Requestify/issues/37

https://mclo.gs/ZVUB3Fu

Perhaps something is outdated which still requires the old RS. Any ideas?

**Comment by embeddedt** [comment]
I think my fork of it should still work? https://github.com/embeddedt/RS-Requestify/releases/tag/v2.0.0

**Comment by aking4125** [comment]
Thanks for the response! I'll look into it.

**Comment by aking4125** [comment]
Yep your fork does still work.
