### ISSUE TITLE
Strange redstone bug

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#7]
#### Issue description:
If you put a redstone on the network, after a while it will break

#### Steps to reproduce:
Until I figured out how to reproduce it

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest
- Refined Storage: latest

Does this issue occur on a server? [yes/no] yes

![image](https://user-images.githubusercontent.com/17977139/93577748-1aa28500-f9a5-11ea-88a1-4878aaf9dd93.png)
![image](https://user-images.githubusercontent.com/17977139/93577830-3574f980-f9a5-11ea-91ab-56fff0d23947.png)

**Comment by bigenergy** [comment]
**I figured out how to reproduce**
I specially created redstone dust, it was normal, clicked on the autocraft where it participates, clicked cancel, looked at it in ME and it became bugged
Seems to be the same with the lightstone

**Comment by tth05** [comment]
Looks very weird to me. In all my testing I've never experienced this issue. Can you reproduce this with just RefinedStorage? Also does it break consistently?

**Comment by bigenergy** [comment]
> Looks very weird to me. In all my testing I've never experienced this issue. Can you reproduce this with just RefinedStorage? Also does it break consistently?

It is strange that you cannot reproduce this. I will try to test it again on a clean server with refined

**Comment by bigenergy** [comment]
seems to be fixed in the new version, so far I have not encountered this bug

**Comment by tth05** [comment]
Ok that's nice. I'm guessing this was more of a recipe error or something weird.
