### ISSUE TITLE
Resource deletion bug

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#9]
#### Issue description:
If you connect an Advanced Rolling Machine to the Collector from a refined storage in which there is a template for production from a certain resource, it disappears. There is no autocrafting or import bus, it just takes resources without starting the mechanism.

https://www.youtube.com/watch?v=k8iPTj5RdlY&feature=emb_logo

UPD: I thought that the problem was in the combination of two mods, but the problem turned out to be refined, it removes the resources for which it has a template:...
https://www.youtube.com/watch?v=qjGYYdC2G-g&feature=emb_title

UPD: Changed crafting plates from a compactor / metal former to cutting a block - it also removes iron (even 1-2 pieces that cannot be crafted)
https://www.youtube.com/watch?v=CAM5OlNtc7c&feature=emb_title
The same result comes out if you make copper plates, it takes away all the copper.

Does this issue occur on a server? [yes/no] yes

**Comment by bigenergy** [comment]
Refined Storage does not return buckets when crafting, for example, made an auto delivery of cakes to Kikimurus, it makes 3 buckets, fills with milk (using essence), makes a cake and buckets are lost somewhere in space and time, no import / export tires with buckets etc. buckets are used only in 1 of this craft and should not go anywhere else.

++ after restarting, the system stops seeing boxes (Storage Drawers) that are connected using the "external storage bus"

**Comment by tth05** [comment]
1. Cannot re-produce at all. Have never had this happen in 100h+ using this mod.
2. Buckets are returned perfectly fine for me using the same recipe you described.
3. Never been able to re-produce that either. Always works for me.

The only thing I can think about is you sending me your world if your modpack is public. Other than that I have no idea.

**Comment by tth05** [comment]
@bigenergy Maybe you can try this again with the newest version. I'm not sure if that fixes any of this but it's worth a try.

**Comment by bigenergy** [comment]
@tth05 I'll try to check it out today

**Comment by bigenergy** [comment]
@tth05 not fixed
see a video https://www.youtube.com/watch?v=ezUUoThZ364

**Comment by bigenergy** [comment]
more details heve https://www.youtube.com/watch?v=uOY68KMAFtc

**Comment by tth05** [comment]
Ok now that made it a lot clearer. I just didn't understand it correctly before. Easy fix, should be out some time tomorrow!

**Comment by tth05** [comment]
fixed in 30ec9454dd705070f69a88c06445efc2239056ed

**Comment by tth05** [comment]
Release will follow. I just want to fix something else first.
